name:                blipboard
version:             0.1.0.0
github:              "3goliad/blipboard"
license:             BSD3
author:              "Javier Maldonado"
maintainer:          "3goliad@gmail.com"
copyright:           "UNLICENSED"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/3goliad/blipboard#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- dhall
- uuid
- random
- cassava
- containers
- hourglass
- text


library:
  source-dirs: src
  default-extensions: NoImplicitPrelude, OverloadedStrings

executables:
  blipboard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blipboard

tests:
  blipboard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blipboard
